/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package strava3golang

import (
	"encoding/json"
)

// checks if the MetaActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaActivity{}

// MetaActivity struct for MetaActivity
type MetaActivity struct {
	// The unique identifier of the activity
	Id *int64 `json:"id,omitempty"`
}

// NewMetaActivity instantiates a new MetaActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaActivity() *MetaActivity {
	this := MetaActivity{}
	return &this
}

// NewMetaActivityWithDefaults instantiates a new MetaActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaActivityWithDefaults() *MetaActivity {
	this := MetaActivity{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MetaActivity) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaActivity) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MetaActivity) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *MetaActivity) SetId(v int64) {
	o.Id = &v
}

func (o MetaActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableMetaActivity struct {
	value *MetaActivity
	isSet bool
}

func (v NullableMetaActivity) Get() *MetaActivity {
	return v.value
}

func (v *NullableMetaActivity) Set(val *MetaActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaActivity(val *MetaActivity) *NullableMetaActivity {
	return &NullableMetaActivity{value: val, isSet: true}
}

func (v NullableMetaActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


