openapi: 3.0.1
info:
  description: "The [Swagger Playground](https://developers.strava.com/playground)\
    \ is the easiest way to familiarize yourself with the Strava API by submitting\
    \ HTTP requests and observing the responses before you write any client code.\
    \ It will show what a response will look like with different endpoints depending\
    \ on the authorization scope you receive from your athletes. To use the Playground,\
    \ go to https://www.strava.com/settings/api and change your “Authorization Callback\
    \ Domain” to developers.strava.com. Please note, we only support Swagger 2.0.\
    \ There is a known issue where you can only select one scope at a time. For more\
    \ information, please check the section “client code” at https://developers.strava.com/docs."
  title: Strava API v3
  version: 3.0.0
servers:
- url: https://www.strava.com/api/v3
security:
- strava_oauth:
  - public
paths:
  /athletes/{id}/stats:
    get:
      description: Returns the activity stats of an athlete. Only includes data from
        activities set to Everyone visibilty.
      operationId: getStats
      summary: Get Athlete Stats
      tags:
      - Athletes
  /athlete:
    get:
      description: Returns the currently authenticated athlete. Tokens with profile:read_all
        scope will receive a detailed athlete representation; all others will receive
        a summary representation.
      operationId: getLoggedInAthlete
      summary: Get Authenticated Athlete
      tags:
      - Athletes
    put:
      description: Update the currently authenticated athlete. Requires profile:write
        scope.
      operationId: updateLoggedInAthlete
      summary: Update Athlete
      tags:
      - Athletes
  /athlete/zones:
    get:
      description: Returns the the authenticated athlete's heart rate and power zones.
        Requires profile:read_all.
      operationId: getLoggedInAthleteZones
      summary: Get Zones
      tags:
      - Athletes
  /segments/{id}:
    get:
      description: "Returns the specified segment. read_all scope required in order\
        \ to retrieve athlete-specific segment information, or to retrieve private\
        \ segments."
      operationId: getSegmentById
      summary: Get Segment
      tags:
      - Segments
  /segments/starred:
    get:
      description: List of the authenticated athlete's starred segments. Private segments
        are filtered out unless requested by a token with read_all scope.
      operationId: getLoggedInAthleteStarredSegments
      summary: List Starred Segments
      tags:
      - Segments
  /segments/{id}/starred:
    put:
      description: Stars/Unstars the given segment for the authenticated athlete.
        Requires profile:write scope.
      operationId: starSegment
      summary: Star Segment
      tags:
      - Segments
  /segment_efforts:
    get:
      description: Returns a set of the authenticated athlete's segment efforts for
        a given segment.  Requires subscription.
      operationId: getEffortsBySegmentId
      summary: List Segment Efforts
      tags:
      - SegmentEfforts
  /segments/explore:
    get:
      description: Returns the top 10 segments matching a specified query.
      operationId: exploreSegments
      summary: Explore segments
      tags:
      - Segments
  /segment_efforts/{id}:
    get:
      description: Returns a segment effort from an activity that is owned by the
        authenticated athlete. Requires subscription.
      operationId: getSegmentEffortById
      summary: Get Segment Effort
      tags:
      - SegmentEfforts
  /activities:
    post:
      description: "Creates a manual activity for an athlete, requires activity:write\
        \ scope."
      operationId: createActivity
      summary: Create an Activity
      tags:
      - Activities
  /activities/{id}:
    get:
      description: Returns the given activity that is owned by the authenticated athlete.
        Requires activity:read for Everyone and Followers activities. Requires activity:read_all
        for Only Me activities.
      operationId: getActivityById
      summary: Get Activity
      tags:
      - Activities
    put:
      description: Updates the given activity that is owned by the authenticated athlete.
        Requires activity:write. Also requires activity:read_all in order to update
        Only Me activities
      operationId: updateActivityById
      summary: Update Activity
      tags:
      - Activities
  /athlete/activities:
    get:
      description: Returns the activities of an athlete for a specific identifier.
        Requires activity:read. Only Me activities will be filtered out unless requested
        by a token with activity:read_all.
      operationId: getLoggedInAthleteActivities
      summary: List Athlete Activities
      tags:
      - Activities
  /activities/{id}/laps:
    get:
      description: Returns the laps of an activity identified by an identifier. Requires
        activity:read for Everyone and Followers activities. Requires activity:read_all
        for Only Me activities.
      operationId: getLapsByActivityId
      summary: List Activity Laps
      tags:
      - Activities
  /activities/{id}/zones:
    get:
      description: Summit Feature. Returns the zones of a given activity. Requires
        activity:read for Everyone and Followers activities. Requires activity:read_all
        for Only Me activities.
      operationId: getZonesByActivityId
      summary: Get Activity Zones
      tags:
      - Activities
  /activities/{id}/comments:
    get:
      description: Returns the comments on the given activity. Requires activity:read
        for Everyone and Followers activities. Requires activity:read_all for Only
        Me activities.
      operationId: getCommentsByActivityId
      summary: List Activity Comments
      tags:
      - Activities
  /activities/{id}/kudos:
    get:
      description: Returns the athletes who kudoed an activity identified by an identifier.
        Requires activity:read for Everyone and Followers activities. Requires activity:read_all
        for Only Me activities.
      operationId: getKudoersByActivityId
      summary: List Activity Kudoers
      tags:
      - Activities
  /clubs/{id}:
    get:
      description: Returns a given club using its identifier.
      operationId: getClubById
      summary: Get Club
      tags:
      - Clubs
  /clubs/{id}/members:
    get:
      description: Returns a list of the athletes who are members of a given club.
      operationId: getClubMembersById
      summary: List Club Members
      tags:
      - Clubs
  /clubs/{id}/admins:
    get:
      description: Returns a list of the administrators of a given club.
      operationId: getClubAdminsById
      summary: List Club Administrators
      tags:
      - Clubs
  /clubs/{id}/activities:
    get:
      description: Retrieve recent activities from members of a specific club. The
        authenticated athlete must belong to the requested club in order to hit this
        endpoint. Pagination is supported. Athlete profile visibility is respected
        for all activities.
      operationId: getClubActivitiesById
      summary: List Club Activities
      tags:
      - Clubs
  /athlete/clubs:
    get:
      description: Returns a list of the clubs whose membership includes the authenticated
        athlete.
      operationId: getLoggedInAthleteClubs
      summary: List Athlete Clubs
      tags:
      - Clubs
  /gear/{id}:
    get:
      description: Returns an equipment using its identifier.
      operationId: getGearById
      summary: Get Equipment
      tags:
      - Gears
  /routes/{id}:
    get:
      description: Returns a route using its identifier. Requires read_all scope for
        private routes.
      operationId: getRouteById
      summary: Get Route
      tags:
      - Routes
  /athletes/{id}/routes:
    get:
      description: Returns a list of the routes created by the authenticated athlete.
        Private routes are filtered out unless requested by a token with read_all
        scope.
      operationId: getRoutesByAthleteId
      summary: List Athlete Routes
      tags:
      - Routes
  /routes/{id}/export_gpx:
    get:
      description: Returns a GPX file of the route. Requires read_all scope for private
        routes.
      operationId: getRouteAsGPX
      summary: Export Route GPX
      tags:
      - Routes
  /routes/{id}/export_tcx:
    get:
      description: Returns a TCX file of the route. Requires read_all scope for private
        routes.
      operationId: getRouteAsTCX
      summary: Export Route TCX
      tags:
      - Routes
  /uploads:
    post:
      description: Uploads a new data file to create an activity from. Requires activity:write
        scope.
      operationId: createUpload
      summary: Upload Activity
      tags:
      - Uploads
  /uploads/{uploadId}:
    get:
      description: Returns an upload for a given identifier. Requires activity:write
        scope.
      operationId: getUploadById
      summary: Get Upload
      tags:
      - Uploads
  /activities/{id}/streams:
    get:
      description: Returns the given activity's streams. Requires activity:read scope.
        Requires activity:read_all scope for Only Me activities.
      operationId: getActivityStreams
      summary: Get Activity Streams
      tags:
      - Streams
  /segment_efforts/{id}/streams:
    get:
      description: Returns a set of streams for a segment effort completed by the
        authenticated athlete. Requires read_all scope.
      operationId: getSegmentEffortStreams
      summary: Get Segment Effort Streams
      tags:
      - Streams
  /segments/{id}/streams:
    get:
      description: Returns the given segment's streams. Requires read_all scope for
        private segments.
      operationId: getSegmentStreams
      summary: Get Segment Streams
      tags:
      - Streams
  /routes/{id}/streams:
    get:
      description: Returns the given route's streams. Requires read_all scope for
        private routes.
      operationId: getRouteStreams
      summary: Get Route Streams
      tags:
      - Streams
components:
  securitySchemes:
    strava_oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://www.strava.com/api/v3/oauth/authorize
          scopes:
            read: "Read public segments, public routes, public profile data, public\
              \ posts, public events, club feeds, and leaderboards"
            read_all: "Read private routes, private segments, and private events for\
              \ the user"
            profile:read_all: Read all profile information even if the user has set
              their profile visibility to Followers or Only You
            profile:write: "Update the user's weight and Functional Threshold Power\
              \ (FTP), and access to star or unstar segments on their behalf"
            activity:read: "Read the user's activity data for activities that are\
              \ visible to Everyone and Followers, excluding privacy zone data"
            activity:read_all: "The same access as activity:read, plus privacy zone\
              \ data and access to read the user's activities with visibility set\
              \ to Only You"
            activity:write: "Access to create manual activities and uploads, and access\
              \ to edit any activities that are visible to the app, based on activity\
              \ read access level"
          tokenUrl: https://www.strava.com/api/v3/oauth/token
      type: oauth2
x-original-swagger-version: "2.0"
